import React, { useState, useEffect, useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import api from '../api/axios';
import TaskCard from '../components/TaskCard';
import TaskForm from '../components/TaskForm';
import { LogOut, Plus, Search } from 'lucide-react';

const Dashboard = () => {
  const { logout, user } = useContext(AuthContext);
  const [tasks, setTasks] = useState([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState('');
  
  // Modal states
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [editingTask, setEditingTask] = useState(null);

  const fetchTasks = async (query = '') => {
    setLoading(true);
    try {
      const { data } = await api.get(`/tasks?keyword=${query}&limit=20`); // Requesting up to 20 for now.
      setTasks(data.data || []);
    } catch (err) {
      console.error('Failed to fetch tasks', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchTasks();
  }, []);

  const handleSearch = (e) => {
    e.preventDefault();
    fetchTasks(search);
  };

  const handleCreateTask = async (taskData) => {
    try {
      await api.post('/tasks', taskData);
      setIsFormOpen(false);
      fetchTasks();
    } catch (err) {
      alert(err.response?.data?.message || 'Failed to create task');
    }
  };

  const handleUpdateTask = async (taskData) => {
    try {
      // Backend uses 'id' instead of '_id' typically generated by mongo, check Task Model
      // Controller uses findOneAndUpdate({ id: id_ }). Ensure `taskData.id` is passed correctly
      await api.patch(`/tasks/${taskData.id}`, taskData);
      setIsFormOpen(false);
      setEditingTask(null);
      fetchTasks();
    } catch (err) {
      alert(err.response?.data?.message || 'Failed to update task');
    }
  };

  const handleDeleteTask = async (taskId) => {
    if (window.confirm('Are you sure you want to delete this task?')) {
      try {
        await api.delete(`/tasks/${taskId}`);
        fetchTasks();
      } catch (err) {
        alert(err.response?.data?.message || 'Failed to delete task');
      }
    }
  };

  const openEditModal = (task) => {
    setEditingTask(task);
    setIsFormOpen(true);
  };

  const openCreateModal = () => {
    setEditingTask(null);
    setIsFormOpen(true);
  };

  return (
    <div className="page-container">
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '3rem', paddingBottom: '1rem', borderBottom: '1px solid var(--glass-border)' }}>
        <div>
          <h1 style={{ fontSize: '2rem', fontWeight: 700, background: 'linear-gradient(135deg, var(--accent-primary), var(--accent-secondary))', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' }}>
            TaskMaster Suite
          </h1>
          <p style={{ color: 'var(--text-secondary)' }}>Welcome back, {user?.email || 'User'}</p>
        </div>
        <button onClick={logout} className="btn-secondary" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <LogOut size={18} /> Logout
        </button>
      </header>

      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem', flexWrap: 'wrap', gap: '1rem' }}>
        <form onSubmit={handleSearch} style={{ display: 'flex', gap: '0.5rem', flex: '1', maxWidth: '400px' }}>
          <div style={{ position: 'relative', width: '100%' }}>
            <Search size={18} color="var(--text-secondary)" style={{ position: 'absolute', left: '1rem', top: '50%', transform: 'translateY(-50%)' }} />
            <input type="text" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search tasks..." className="input-field" style={{ paddingLeft: '2.5rem' }} />
          </div>
          <button type="submit" className="btn-secondary">Search</button>
        </form>

        <button onClick={openCreateModal} className="btn-primary" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <Plus size={18} /> New Task
        </button>
      </div>

      {loading ? (
        <div style={{ textAlign: 'center', padding: '4rem', color: 'var(--text-secondary)' }}>Loading your dashboard...</div>
      ) : tasks.length === 0 ? (
        <div style={{ textAlign: 'center', padding: '4rem', background: 'var(--glass-bg)', borderRadius: 'var(--radius-lg)', border: '1px dashed var(--glass-border)' }}>
          <p style={{ color: 'var(--text-secondary)', marginBottom: '1rem' }}>No tasks found.</p>
          <button onClick={openCreateModal} className="btn-primary" style={{ display: 'inline-flex', alignItems: 'center', gap: '0.5rem' }}>
            <Plus size={18} /> Create Your First Task
          </button>
        </div>
      ) : (
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))', gap: '1.5rem' }}>
          {tasks.map(task => (
            <TaskCard 
              key={task._id || task.id} 
              // Normalize id for the delete update handlers if needed. 
              // The backend model seems to use `id` for identifying operations in the findOneAndUpdate. Let's make sure it's passed.
              task={{...task, id: task.id || task._id}} 
              onEdit={openEditModal} 
              onDelete={handleDeleteTask} 
            />
          ))}
        </div>
      )}

      {isFormOpen && (
        <TaskForm 
          initialData={editingTask} 
          onSubmit={editingTask ? handleUpdateTask : handleCreateTask} 
          onClose={() => setIsFormOpen(false)} 
        />
      )}
    </div>
  );
};

export default Dashboard;
